#!/usr/bin/env bash
# stopped our 4-to_infinity_and_beyond process
# using ctrl+c in the previous task
# Replace <PID> with the actual process ID of the "4-to_infinity_and_beyond" process

kill "$(pgrep -f 4-to_infinity_and_beyond)"
